mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

from survey import urls

urlpatterns = [
    path('admin/', admin.site.urls),

    path('survey/', include('survey.urls'), name='survey'),
]

mysite/survey/urls.py
from django.urls import path

from . import views

app_name = 'survey'
urlpatterns = [
    path('', views.home, name='home'),

    path('<slug:survey>/', views.list_survey, name='list_survey'),

    path('<slug:survey>/comment/', views.survey_comment, name='survey_comment'),
]

mysite/survey/models.py
# Create your models here.

from django.db import models
from django.utils import timezone
from django.urls import reverse
from django.contrib.auth.models import User


# Create your models here.

class Survey(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='survey')
    slug = models.SlugField(max_length=100)
    publish = models.DateTimeField(default=timezone.now)

    class Meta:
        ordering = ['-publish']


    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('survey:list_survey', args=[self.slug])



class PostQuestion(models.Model):
    text = models.TextField()
    survey = models.ForeignKey(Survey, on_delete=models.CASCADE, null=True, related_name='questions')

    def __str__(self):
        return self.text



class PostAnswer(models.Model):
    text = models.TextField()
    question = models.ForeignKey(PostQuestion, on_delete=models.CASCADE, related_name='answers')

    def __str__(self):
        return self.text

class Comment(models.Model):
    name = models.CharField(max_length=80)
    body = models.TextField()
    survey = models.ForeignKey(Survey, on_delete=models.CASCADE, related_name='comments')
    created_on = models.DateTimeField(auto_now_add=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ['created_on']

    def __str__(self):
        return f'Comment {self.body} by {self.name}'

mysite/survey/forms.py
from django import forms
from .models import Comment

class CommentForm(forms.ModelForm):
        class Meta:
            model = Comment
            fields = ['name', 'body']

mysite/survey/views.py
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator, PageNotAnInteger
from django.views.decorators.http import require_POST
from survey.forms import CommentForm
from survey.models import Survey


# Create your views here.
@require_POST
def survey_comment(request, survey_id):
    survey = get_object_or_404(Survey, id=survey_id)
    comment = None
    form = CommentForm(request.POST)

    if form.is_valid():
        comment = form.save(commit=False)
        comment.survey = survey
        comment.save()

    return render(request, 'survey/comment.html', {'survey': survey,
                                                                        'form': form,
                                                                        'comment': comment,
                                                                        })

def home(request):
    survey = Survey.objects.all()
    paginator = Paginator(survey, 3)
    page = request.GET.get('page')

    try:
        survey = paginator.page(page)
    except PageNotAnInteger:
        survey = paginator.page(1)

    return render(request, 'survey/home.html', {'survey': survey})


def list_survey(request, survey):
    survey = get_object_or_404(Survey, slug=survey)
    questions = survey.questions.all().prefetch_related('answers')

    questions_with_answers = []
    for quest in questions:
        answers = quest.answers.all()
        questions_with_answers.append({
            'question': quest,
            'answers': answers
        })

    comments = survey.comments.filter(active=True)
    form = CommentForm()


    return render(request, 'survey/list_survey.html', {'survey': survey,
                                                                        'questions': questions,
                                                                        'comments': comments,
                                                                        'form': form,
                                                                        'questions_with_answers': questions_with_answers,
                                                                        })

mysite/survey/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ru" data-theme="light">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %} {% endblock %}| PollHub</title>
    <link href=" {% static 'css/style.css' %}" rel="stylesheet">
</head>
<body>
    <!-- Шапка -->
    <header class="poll-header">
        <div class="poll-logo">
            {# Заменить на логотип #}
            <span>PollHub</span>
        </div>
        <nav class="poll-nav">
            <!-- Динамическое меню -->
            {% block menu %}
            {% endblock %}
        </nav>
    </header>

    <!-- Основной контент -->
    <main class="poll-container">
        <h1>{{ page_heading }}</h1>

        <!-- Сетка опросов -->
        <div class="poll-grid">
            {% block survey %}
            {% endblock %}
        </div>
    </main>

    <!-- Подвал -->
    <footer class="poll-footer">
{#        <p>&copy; {{ current_year }} PollHub. Все права защищены</p>#}
        {% block footer %}{% endblock %}
    </footer>
</body>
</html>

mysite/survey/templates/pagination.html
<div class="pagination">
    <span class="step_links">
        {% if page.has_previous %}
            <a href="?page={{ page.previous_page_number }}">Previous</a>
        {% endif %}
        <span class="current">
          Page {{ page.number }} of {{ page.paginator.num_pages }}.
        </span>
        {% if page.has_next %}
            <a href="?page={{ page.next_page_number }}">Next</a>
        {% endif %}
    </span>
</div>

mysite/survey/templates/survey/comment.html
{% extends 'base.html' %}

{% block survey %}
    <article class="survey-card">
    {% if comment %}
        <h2>Ваш комментарий успешно добавлен</h2>
        <p><a href="{{ survey.get_absolute_url }}">Вернуться к опросу "{{ survey.title }}"</a></p>
        {% else %}
        {% include 'survey/includes/comment_form.html' %}
    {% endif %}
    </article>
{% endblock %}

mysite/survey/templates/survey/home.html
{% extends 'base.html' %}

{% block menu %}
    {% for link in nav_links %}
        <a href="{{ link.url }}">{{ link.title }}</a>
    {% endfor %}
{% endblock %}



{% block survey %}
    {% for surv in survey %}
        <article class="survey-card">
            <h3>{{ surv.title }}</h3>
            <p>{{ surv.content }}</p>
                <a href="{{ surv.get_absolute_url }}">
                    <button class="poll-btn">
                    Пройти Опрос
                    </button>
                </a>
        </article>
    {% empty %}
        <p>Нет доступных опросов</p>
    {% endfor %}
        {% include 'pagination.html' with page=survey %}
{% endblock %}

mysite/survey/templates/survey/includes/comment_form.html
<h2>Добавить комментарий</h2>
<form action="{% url "survey:survey_comment" survey.slug %}" method="post">
    {{ form.as_p }}
    {% csrf_token %}
    <p><input type="submit" value="Add comment"></p>
</form>

mysite/survey/templates/survey/list_survey.html
{% extends 'base.html' %}


{% block survey %}
<article class="survey-container">
    <!-- Заголовок опроса -->
    <header class="survey-header">
        <h1 class="survey-title">{{ survey.title }}</h1>
        {% if survey.content %}
        <p class="survey-description">{{ survey.content }}</p>
        {% endif %}
    </header>

    <!-- Форма опроса -->
    <form method="POST" class="survey-form">
        {% csrf_token %}

        <!-- Список вопросов -->
        {% for quest in questions %}
        <section class="question-card">
            <h2 class="question-title">{{ quest.text }}</h2>

            <!-- Варианты ответов -->
            <div class="answers-list">
                {% for answer in questions_with_answers %}
                <div class="answer-item">
                    {% if question.multiple_choice %}
                    <input type="checkbox"
                           name="question_{{ quest.id }}"
                           id="answer_{{ answer.id }}"
                           value="{{ answer.id }}">
                    {% else %}
                    <input type="radio"
                           name="question_{{ quest.id }}"
                           id="answer_{{ answer.id }}"
                           value="{{ answer.id }}"
                           required>
                    {% endif %}

                    <label for="answer_{{ answer.id }}" class="answer-label">
                        <span class="custom-check"></span>
                        {{ answer.text }}
                    </label>
                </div>
                {% endfor %}
            </div>
        </section>
        {% endfor %}

        <!-- Кнопка отправки -->
        <div class="submit-section">
            <button type="submit" class="submit-btn">
                Отправить ответы
            </button>
        </div>
    </form>

</article>
{% endblock %}

{% block footer %}
    {% with comments.count as total_comments %}
        <h2>
            {{ total_comments }} comment{{ total_comments|pluralize }}
        </h2>
    {% endwith %}
{% for comment in comments %}
    <div class="comment">
        <p class="info">
            Comment {{ forloop.counter }} by {{ comment.name }}
            {{ comment.created }}
        </p>
        {{ comment.body|linebreaks }}
    </div>
{% empty %}
    <p>There are no comments.</p>
{% endfor %}
{% endblock %}